# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1
epsilon_finish: 0.05
epsilon_anneal_time: 100000

runner: "episode"
batch_size: 128
# Change Replay buffer size to 8*
buffer_size: 5000
rnn_hidden_dim: 256
# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
mixer: "qmix"
mixing_embed_dim: 64
hypernet_layers: 1
hypernet_embed: 256
lr: 0.001
double_q: False
td_lambda: 0.4

name: "qmix_large"
